### ISSUE TITLE
Run this on Android phones

### ISSUE THREAD

**Issue by mananwason** [waveform80/compoundpi#46]
Hi @waveform80. I was wondering if this project can be run on android somehow by treating the phones as servers? Cheers :smile:

**Comment by waveform80** [comment]
I suppose the phone could potentially be a *client* controlling the Pi servers, but the server is very specific to the picamera module (which only supports the Pi's camera module, and only operates on a Pi).

**Comment by mananwason** [comment]
okay thanks.
