### ISSUE TITLE
Error while downloading captures from servers 

### ISSUE THREAD

**Issue by mananwason** [waveform80/compoundpi#47]
@waveform80 I am facing this error while downloading images from the server using a python script. Can you help me here? I have followed the documentation strictly.
```IOError: [Errno 2] No such file or directory: '192.168.43.171-0.jpg'```

**Comment by waveform80** [comment]
Can you post the code you're using?

**Comment by mananwason** [comment]
Sure. This is the code I'm running. Just basic capturing and downloading.
```
from compoundpi.client import CompoundPiClient
import io
client = CompoundPiClient()
try:
    	client.servers.network = '192.168.43.1/24'
    	#client.servers.output = '/home/manan/Desktop/captures'
    	client.servers.find(10)
    	client.capture()
	for addr, files in client.list().items():
       	 for f in files:
            print('Downloading image %d from %s (%d bytes)' % (
                f.index,
                addr,
                f.size,
                ))
            with io.open('%s-%d.jpg' % (addr, f.index)) as f:
                client.download(addr, f.index, f)
finally:
    client.clear()	
    client.close()

```

**Comment by waveform80** [comment]
Ah, you're missing the file mode in `io.open`. This defaults to `'r'` (read) so you're attempting to open "192.168.43.171-0.jpg" for reading and, naturally, it doesn't exist so you wind up with a no such file or directory error. Just add a `'wb'` parameter to the `io.open` call and you should be good to go.

**Comment by mananwason** [comment]
Oh this is solved the problem but another I got another one now. It prints the index but shows this error as well. 
```AttributeError: '_io.BufferedWriter' object has no attribute 'index'
```

**Comment by waveform80** [comment]
Ah indeed - you've called the open file object `f` which overwrites the file metadata object `f`. Hence, when it goes to look for `f.index` within the `with` clause you get an attribute error. I'd suggest calling the open file object something else (have a look at the first example in http://compoundpi.readthedocs.org/en/release-0.4/batch.html#examples which uses "output" as the name instead)

**Comment by mananwason** [comment]
Oh yeah. That was the issue. Now it is working fine. But I also need the epoch time in the name of the file. How can I do that?

**Comment by waveform80** [comment]
Assuming by "epoch time" you mean "seconds since the UNIX epoch" (i.e. a UNIX timestamp), `f.timestamp` will contain the capture timestamp as a `datetime` object so you could do something like:

```python
with io.open('%s-%d-%d.jpg' % (addr, f.index, f.timestamp.timestamp())) as output:
    client.download(addr, f.index, output)
```

**Comment by mananwason** [comment]
I had tried doing this earlier but what I got was ``` AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
```
I googled it but didn't find any conclusive answers.

**Comment by waveform80** [comment]
Are you perhaps using Python 2? The `timestamp` method for `datetime` objects was only added in Python 3. In Python 2 you'd need to do something like:

```python
from time import mktime

...

with io.open('%s-%d-%d.jpg' % (addr, f.index, mktime(f.timestamp.timetuple()))) as output:
    client.download(addr, f.index, output)
```

**Comment by mananwason** [comment]
oh yeah !! Thanks for your help!!
